# These are supported funding model platforms

github: Ruddickmg
patreon: Ruddickmg
open_collective: # your-open-collective-username
ko_fi: # your-ko-fi-username
tidelift: # platform/name
community_bridge: # project-name
liberapay: # your-liberapay-username
issuehunt: # your-issuehunt-username
lfx_crowdfunding: # project-name
polar: # your-polar-username
buy_me_a_coffee: # your-bmc-username
thanks_dev: u/gh/Ruddickmg
custom: # "https://www.paypal.me/your-username"
