#!/bin/sh
set -e

VERSION=$(cat target/release/version.txt)
if [ -z "$VERSION" ]; then
  echo "No version to publish"
  exit 0
fi

echo "Updating nix hashes for v${VERSION}"

# Install jq for JSON manipulation
nix profile install nixpkgs#jq

# Read sources.json from workspace (generated by release job, has binary hashes)
SOURCES=$(cat target/release/sources.json)

# Compute source hash for fetchFromGitHub
SOURCE_URL="https://github.com/Ruddickmg/hermes.nvim/archive/refs/tags/v${VERSION}.tar.gz"
echo "Prefetching source tarball..."
SOURCE_HASH_NIX32=$(nix-prefetch-url --unpack "$SOURCE_URL" --type sha256 | tail -1)

# Convert nix base32 to SRI format
SOURCE_HASH_SRI=$(nix hash to-sri --type sha256 "$SOURCE_HASH_NIX32")
echo "Source hash: $SOURCE_HASH_SRI"

# Write final sources.json to temp file (with source hash)
SOURCES_TMP=$(mktemp)
echo "$SOURCES" | jq --arg hash "$SOURCE_HASH_SRI" '. + { source: { hash: $hash } }' > "$SOURCES_TMP"

echo "Final sources.json:"
cat "$SOURCES_TMP"

# Compute hash of sources.json itself (for fetchurl in default.nix)
SOURCES_HASH_B16=$(sha256sum "$SOURCES_TMP" | awk '{print $1}')
SOURCES_HASH_SRI="sha256-$(printf "$(echo "$SOURCES_HASH_B16" | sed 's/\([0-9a-f][0-9a-f]\)/\\x\1/g')" | base64 | tr -d '\n')"
echo "sources.json hash: $SOURCES_HASH_SRI"

rm -f "$SOURCES_TMP"

# Update default.nix with new version and sources.json hash
sed -i "s/version = \".*\"/version = \"$VERSION\"/" nix/packaging/default.nix
sed -i "s|hash = \".*\"|hash = \"$SOURCES_HASH_SRI\"|" nix/packaging/default.nix

echo "Final default.nix:"
cat nix/packaging/default.nix

# Commit with [skip ci]
git config user.email "ci@hermes.nvim"
git config user.name "Hermes CI"
git add nix/packaging/default.nix
git commit -m "nix: update hermes-nvim to v${VERSION} [skip ci]"
git push origin HEAD
